### ISSUE TITLE
Upgrade to React@16

### ISSUE THREAD

**Issue by benjycui** [benjycui/bisheng#102]
Ref: https://facebook.github.io/react/docs/react-dom-server.html

And then, we can use `renderToNodeStream` to improve build performance.

**Comment by silentcloud** [comment]
这个进度怎么样了？ @benjycui 

我们需要在 antd-mobile 里调

**Comment by benjycui** [comment]
`0.26.0` 只升级 react，还没有做性能优化。

**Comment by jljsj33** [comment]
26 到 27 搞个更新文档，怎么升，一头雾水。。。

**Comment by benjycui** [comment]
@jljsj33 因为我自己都没升级过，等 ant-design 升级后，我发个 diff 你吧。。

**Comment by jljsj33** [comment]
@benjycui OK

**Comment by silentcloud** [comment]
mobile 现在也是同样的问题

**Comment by benjycui** [comment]
ant-design 和 ant-design-mobiel 都需要等 antd-tools 升级到 webpack@3 先。

**Comment by lili21** [comment]
可不可以提供options让开发者选择react的版本？最终生成的_sites里的react版本。
