### ISSUE TITLE
bisheng 本地调试问题

### ISSUE THREAD

**Issue by afc163** [benjycui/bisheng#113]
- [ ] 先 npm run site 构建出 _site，然后 npm start 启动，访问 http://localhost:8001/components/form-cn/ 页面，可以看到 select 组件的箭头位置异常。（移除 _site 后重启正常）

https://github.com/ant-design/ant-design/tree/antd-3.0

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/fe7386746cfe7123c7628749d501a3141b19cf6c

**Comment by afc163** [comment]
略粗暴。。

**Comment by benjycui** [comment]
事实上本地测试时，网页都打不开，_site 内的文件优先级在 webpack-dev-server 内存里面的要高，么办法。
