### ISSUE TITLE
在服务器上运行 build， 除了 _site 空目录外没有生成任何文件

### ISSUE THREAD

**Issue by pciapcib** [benjycui/bisheng#117]
在服务器上尝试了 antd 以及其他项目，都有这个问题。在本地 macOS 上没有问题。

``` bash
$ git clone https://github.com/ant-design/ant-design.git
$ npm install
$ npm run site
```

Node 环境：
1. 9.2.0
2. 6.10.2

系统环境：
1. Ubuntu 16.04.1 LTS
2. Linux whale.server01 3.10.0-327.el7.x86_64 GNU/Linux

![wx20171129-100936](https://user-images.githubusercontent.com/16255397/33354351-6ec1079a-d4ed-11e7-9a2a-a96649a416b2.png)

**Comment by benjycui** [comment]
这种问题我这边无法排查，猜测原因可能是 bisheng 运行时没有写入权限。你还是自行研究吧，不好意思。

**Comment by FrankPaul1** [comment]
@pciapcib 我这边也遇到了相同的问题，请问后面解决了吗？

**Comment by pciapcib** [comment]
@FrankPaul1 没有，不过在另一台 Ubuntu 的服务器上却没有发现这个问题。最后我是把本地编译后的 `_site` 通过 `scp` 传到服务器上的。
