### ISSUE TITLE
bisheng.config.js的source选项的问题

### ISSUE THREAD

**Issue by mengch** [benjycui/bisheng#120]
source选项用默认的posts目录没问题，把source的目录改成其他名字之后，启动之后，点击对应的文章链接，显示404.
```
ok: // source: './posts'
404: //source: './posts1'
404: // source: {test: [
    'test.md',
    'test1.md'
]}
```
改回posts之后正常，修改成其他的就是404.

**Comment by benjycui** [comment]
路由没配置好吧，提供信息不足，只能靠猜。

**Comment by mengch** [comment]
```
module.exports = {
    source: './posts',
    output: './_site',
    theme: 'bisheng-theme-one',
    port: 8000,
};
```
这个是我的bisheng.config.js，这个是正常的。

这个是不正常的，其他的所有内容都没有修改，只有source的目录改了下名字，然后md文章就是404了。
```
module.exports = {
    source: './posts1',
    output: './_site',
    theme: 'bisheng-theme-one',
    port: 8000,
};
```
经过测试，在bisheng-example的bisheng.config.js里面修改source的值，也是一样的结果，404。
[bisheng-example-config](https://github.com/benjycui/bisheng/blob/master/packages/bisheng-example/bisheng.config.js#L16) 修改内容也是修改post目录名，把source字段加到config中，没有其他任何改动。要不您在本地试下看有没有这个问题

**Comment by benjycui** [comment]
路由： https://github.com/benjycui/bisheng/blob/7c63f382a375e9d2e311d471bd33dae55e487cd5/packages/bisheng-theme-one/src/index.js#L14-L24

Ref: https://github.com/benjycui/bisheng/blob/master/docs/theme.md#indexjs

**Comment by mengch** [comment]
多谢👍另外在主题的使用处可以说一下路由的问题，快速上手里面没有提到使用默认主题的副作用
