### ISSUE TITLE
执行`deploy `后页面“404 Not Found!”

### ISSUE THREAD

**Issue by programmer-yang** [benjycui/bisheng#125]
### 现象
`dev`正常
`build`正常
自己把`build`后的内容放在本地`web容器`下也正常
执行`deploy`后`gitpages`页面异常

### 重现
[项目地址](https://github.com/programmer-yang/test-bisheng)
[git pages页面](https://programmer-yang.github.io/test-bisheng/)

**Comment by benjycui** [comment]
https://github.com/programmer-yang/test-bisheng/blob/master/bisheng.config.js#L19

**Comment by programmer-yang** [comment]
@benjycui 感谢感谢，已经解决了我的问题

**Comment by HeartLee** [comment]
> @benjycui 感谢感谢，已经解决了我的问题

你好，请问这个问题的原因是什么？

**Comment by HeartLee** [comment]
> @benjycui 感谢感谢，已经解决了我的问题

@programmer-yang 你好，请问具体是怎么解决的
