### ISSUE TITLE
config中devServerConfig可不可以调整优先级？

### ISSUE THREAD

**Issue by yuanhan1890** [benjycui/bisheng#132]
https://github.com/benjycui/bisheng/blob/ab245bc41d85d753616966fc32803ce7e3537c74/packages/bisheng/src/index.js#L79-L86

```js
  var serverOptions = _extends({
    quiet: true
  }, bishengConfig.devServerConfig, {
    contentBase: path.join(process.cwd(), bishengConfig.output),
    historyApiFallback: true,
    hot: true,
    host: 'localhost'
  });
```

**Comment by benjycui** [comment]
使用场景是？

**Comment by yuanhan1890** [comment]
@benjycui ，解决hot reload时发现[webpack-dev-server/issues/364](https://github.com/webpack/#issuecomment-201002156)这个问题。
现在只能通过改`node_module/bisheng`内代码移除`--hot`。
我对`webpack hot reload`不太清楚，也许`[WDS] app updating ...`之后浏览器不刷新并不是因为`--hot`与`hot module replacement plugin`冲突？

**Comment by benjycui** [comment]
来个 PR 把 `hot: true,` 移到 `devServerConfig`  前吧。

**Comment by Saviio** [comment]
@yuanhan1890 我刚修完一个本地的[WDS] app updating后不刷新的场景，如果你也遇到这个问题的话，我这里提供一个思路。

有可能是 node_modules 里存在了多个版本的 webpack (n >=2)，导致了 webpackHotUpdate 这个事件分别被不同的 hotEmitter 实例处理了。

如果你已经解决了, 就当我打扰了- -....

**Comment by yuanhan1890** [comment]
@Saviio , 我仓库里的确有两个webpack版本，但是不知道是不是你说的原因。最近在看webpack底层的东西，你说的hotEmitter我会多注意的，十分感谢～
