### ISSUE TITLE
support react 16.3

### ISSUE THREAD

**Issue by chenshuai2144** [benjycui/bisheng#138]
使用心得 context api 需要16.3

**Comment by benjycui** [comment]
bisheng 并没锁死 React 版本 https://github.com/benjycui/bisheng/blob/master/packages/bisheng/package.json#L95

所以使用 React@16.3 是碰到什么问题了么？

**Comment by chenshuai2144** [comment]
createContext api 未找到！
我用 cdn 引入就可以了

**Comment by benjycui** [comment]
rm -rf node_modules && npm i 试试。
