### ISSUE TITLE
运行 bisheng-example 出现 MIME type 错误

### ISSUE THREAD

**Issue by jyzwf** [benjycui/bisheng#142]
你好，我直接下载了 `bisheng-example`，然后运行，发现会出现如下情况：

<img width="1252" alt="2018-04-24 1 36 59" src="https://user-images.githubusercontent.com/12515800/39167991-9d4b7312-47c4-11e8-989f-1d7a69c2a9db.png">

请问怎么消除呢？谢谢`^_^`

**Comment by benjycui** [comment]
本地运行时，这个文件是不存在的 https://github.com/benjycui/bisheng/issues/110
