### ISSUE TITLE
bisheng-plugin-react的问题

### ISSUE THREAD

**Issue by guoshencheng** [benjycui/bisheng#147]
`bisheng-plugin-react`这个插件接收一个babelConfig的问题，查看了一下，参数是使用loaderUtils来读取的，这个工具似乎不支持读取json类型的数据

```javascript
const babelConfig = JSON.stringify({
  plugins: [
    [
      'import', {
        style: true,
        libraryName: ''xxxx",
        libraryDirectory: 'components',
      },
    ],
  ],
})
```
使用这样的配置在最后解析出来之后，会只截取这一小段`{"plugins":[["import"`，所以会导致代码中的`JSON.parse(babelConfig)`报错，这个问题不知道是不是我使用的问题，如果不是，希望能够修复，或者能想webpack一样，使用object形式的options

**Comment by ruoqianfengshao** [comment]
libraryName: ''xxxx", 你的引号不对吧

**Comment by JiangJun1994** [comment]
@guoshencheng 请问你用 bisheng-plugin-react成功了吗？我看bisheng的文档像下面这样写就可以转换成按钮，为什么我的显示出来还是源码呢？
`
bisheng.config.js配置:

module.exports = {
  plugins: ['bisheng-plugin-react?lang=jsx'],
};

markdown文档内容：
This is a button:

```jsx
import { Button } from 'antd';
ReactDOM.render(<Button>Click!</Button>, mountNode);
```
`

**Comment by guoshencheng** [comment]
@JiangJun1994 bisheng-plugin-react正常使用是没有问题的

**Comment by JiangJun1994** [comment]
> @JiangJun1994 bisheng-plugin-react正常使用是没有问题的

嗯嗯，是因为theme 的原因。
