### ISSUE TITLE
bisheng 是如何把markdown里面的jsx 转化为reactNode的？

### ISSUE THREAD

**Issue by bing1021** [benjycui/bisheng#152]
我看antd react-amap 里面的demos 都有 preview 方法。渲染就是用的这个方法。

我自己的例子里面却没有preview
![Uploading 2882EBCA-7B32-4DC4-80C8-546831CD5A41.png…]()
请问这个preview是如何来的呢？

**Comment by ryan730** [comment]
![image](https://user-images.githubusercontent.com/14855190/45253409-4263b900-b399-11e8-8509-86936eb0fe46.png)
![537b6dde-d7c0-4a45-89ca-df4cf98b39a8](https://user-images.githubusercontent.com/14855190/45253534-86f05400-b39b-11e8-8261-ad44c2dc6b97.png)
看这两个插件就明白了...

**Comment by benjycui** [comment]
楼上正解，涉及到 AST 操作，可以看下 babel 相关的文档。

**Comment by Luin-Li** [comment]
bisheng-plugin-antd插件里面只匹配了demo文件夹下的markdown去提供 preview 方法，所以含jsx代码的md文件要写在demo文件夹下面。我也是一时手贱改了文件夹名字，找到源码才发现的...
