### ISSUE TITLE
babel@7支持

### ISSUE THREAD

**Issue by yxqme** [benjycui/bisheng#153]
能升级到babel@7可吗？

**Comment by hxlniada** [comment]
+1

**Comment by macklay** [comment]
+1

**Comment by benjycui** [comment]
babel 7 + webpack 4 都可以一起升级下。

@afc163 和 @yesmeck 可以帮忙看下？毕竟 antd-tools 里面的依赖也可以升级下了吧。

**Comment by afc163** [comment]
https://github.com/benjycui/bisheng/pull/159
https://github.com/ant-design/antd-tools/pull/79

@chenyang-biu 都已经在做了。

**Comment by chenyang-biu** [comment]
@yxqme  emmm 抱歉, 中间这几天有事情,  已完成  可以审了  @afc163

**Comment by afc163** [comment]
done
