### ISSUE TITLE
bisheng-plugin-react is not work?

### ISSUE THREAD

**Issue by macklay** [benjycui/bisheng#155]
I got bisheng-example code and add simple react code from doc but i see only code without any react render. What am I doing wrong?

```js
module.exports = {
  theme: 'bisheng-theme-one',
  lazyLoad: false,
  plugins: [
    'bisheng-plugin-toc?maxDepth=2',
    'bisheng-plugin-description',
    'bisheng-plugin-react'
    // 'bisheng-plugin-antd'
  ],
```

![image](https://user-images.githubusercontent.com/6972011/46885260-2784d880-ce60-11e8-8365-36d3190ddf99.png)

**Comment by JiangJun1994** [comment]
i meet the same problem, did you resolve it ?

**Comment by macklay** [comment]
> i meet the same problem, did you resolve it ?

Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.

**Comment by JiangJun1994** [comment]
> > i meet the same problem, did you resolve it ?
> 
> Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.

i tried as you said, but failed

**Comment by JiangJun1994** [comment]
> > > i meet the same problem, did you resolve it ?
> > 
> > 
> > Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.
> 
> i tried as you said, but failed

![image](https://user-images.githubusercontent.com/25809468/47093935-c5134a00-d25c-11e8-9b52-8e2c625833e6.png)

**Comment by macklay** [comment]
> > > > i meet the same problem, did you resolve it ?
> > > 
> > > 
> > > Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.
> > 
> > 
> > i tried as you said, but failed
> 
> ![image](https://user-images.githubusercontent.com/25809468/47093935-c5134a00-d25c-11e8-9b52-8e2c625833e6.png)



> > > i meet the same problem, did you resolve it ?
> > 
> > 
> > Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.
> 
> i tried as you said, but failed

Maybe you have wrong lang in md files, it must be ``` react-component
Anyway, I copied plugin code into _theme folder and put plugins settings into _theme/index.js with custom lang:
![image](https://user-images.githubusercontent.com/6972011/47095205-79997580-d235-11e8-880f-f162f127c077.png)

**Comment by JiangJun1994** [comment]
> > > > > i meet the same problem, did you resolve it ?
> > > > 
> > > > 
> > > > Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.
> > > 
> > > 
> > > i tried as you said, but failed
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/25809468/47093935-c5134a00-d25c-11e8-9b52-8e2c625833e6.png)
> 
> > > > i meet the same problem, did you resolve it ?
> > > 
> > > 
> > > Yes, i put 'bisheng-plugin-react' on the first place of the list, and plugin started to work.
> > 
> > 
> > i tried as you said, but failed
> 
> Maybe you have wrong lang in md files, it must be ``` react-component by default.
> Anyway, I copied `bisheng-theme-one` plugin code into _theme folder and put plugins settings into _theme/index.js with custom lang:
> ![image](https://user-images.githubusercontent.com/6972011/47095205-79997580-d235-11e8-880f-f162f127c077.png)
thank you! i resolved it.
