### ISSUE TITLE
把 antd 的项目抽取出来一个最简版本、供其他类似antd项目当脚手架用

### ISSUE THREAD

**Issue by warmhug** [benjycui/bisheng#17]
我尝试抽取了下，报了一堆错~ 帮忙来搞下？造福下别人~

**Comment by benjycui** [comment]
最简版是这个 https://github.com/benjycui/bisheng-theme-one

**Comment by wuguanghai45** [comment]
我抽离了一下
https://github.com/wuguanghai45/antdBishengTheme

**Comment by benjycui** [comment]
@wuguanghai45 其实你这个项目应该叫脚手架，而非 theme

**Comment by wuguanghai45** [comment]
@benjycui  谢谢您的建议，已经改名。如果改的不够好能否给个建议

**Comment by jinyindu** [comment]
这个路由层级只支持一级吗？ 我现在有建了一个文件 例如 packages/react/componets 现在读取路由一直是404
