### ISSUE TITLE
如何把ico图标替换本地的favicon.ico图标

### ISSUE THREAD

**Issue by WangJM001** [benjycui/bisheng#175]
如题

**Comment by lili21** [comment]
定义自己的[htmlTemplate](https://github.com/benjycui/bisheng#htmltemplate-string)即可。

**Comment by WangJM001** [comment]
> 定义自己的[htmlTemplate](https://github.com/benjycui/bisheng#htmltemplate-string)即可。
因为是要用本地的ico，相当是静态文件，不知道怎么把这个ico打到输出包中，要怎么配置

**Comment by WangJM001** [comment]
> 定义自己的[htmlTemplate](https://github.com/benjycui/bisheng#htmltemplate-string)即可。

因为是要用本地的ico，相当是静态文件，不知道怎么把这个ico打到输出包中，要怎么配置

**Comment by lili21** [comment]
你可以直接在`bisheng`构建完成后，自己copy到目录里，也可以用[copy-webpack-plugin](https://github.com/webpack-contrib/copy-webpack-plugin)。方法很多吧。

**Comment by WangJM001** [comment]
谢谢建议，我试试
