### ISSUE TITLE
新文档项目推荐使用bisheng吗？

### ISSUE THREAD

**Issue by 1601bjh** [benjycui/bisheng#176]
要做一个新项目，项目中有个文档页面，决定用bisheng，发现npm的版本很低，请问现在还在维护吗，或者推荐使用吗？

**Comment by LeuisKen** [comment]
还在维护，可以使用。

**Comment by 1601bjh** [comment]
好的，谢谢，我下好包以后，发现一直提示 can't not find module ，这个到底是怎么用的？或者还有什么简单的案例。在线等！。。。急

**Comment by LeuisKen** [comment]
求详细报错信息。

**Comment by UnicornXU** [comment]
> 好的，谢谢，我下好包以后，发现一直提示 can't not find module ，这个到底是怎么用的？或者还有什么简单的案例。在线等！。。。急

大佬最后怎么用的,教我
