### ISSUE TITLE
能否支持插件，读取 ts 文件的 interface + 注释，自动化生成文档。

### ISSUE THREAD

**Issue by DiamondYuan** [benjycui/bisheng#181]
https://github.com/ant-design/ant-design/issues/14940

相关 issue

实现语法

```
---
file: './index.tsx'
interface: Demo
language:zh-cn
---
```
就会自动读取 index.tsx 中叫做 Demo 的 interface ，然后分析注释，转换成 markdown 里面的表格。

实现步骤
1 解析上面的语法，明确 interface 名字，文件路径，语言
2 读取文件 转换成 ast
3 找到 interface ，读取参数，解析各个语言的注释
4 根据配置的语言来生成文档表格。

**Comment by DiamondYuan** [comment]
如果可以的话我会尝试编写代码并且提交 PR。
预计会引入一个 npm 包 ts-simple-ast

**Comment by DiamondYuan** [comment]
@benjycui

**Comment by DiamondYuan** [comment]
学习了源码以后，准备参考 react 的方法。

```typescriptInterface
file: ./index.tsx
interface: Demo
language: zh-cn
```

**Comment by LeuisKen** [comment]
是不是可以借助 bisheng 本身的 plugin 机制来做呢？

**Comment by DiamondYuan** [comment]
> 是不是可以借助 bisheng 本身的 plugin 机制来做呢？

我在开发中，我也是这么想的。

**Comment by DiamondYuan** [comment]
@LeuisKen  plugin 写完了 https://github.com/yuquewebclipper/bisheng-plugin-typescript-interface
