### ISSUE TITLE
bisheng非常严重的bug

### ISSUE THREAD

**Issue by jinyindu** [benjycui/bisheng#193]
bisheng 路由如果配置了多级一直进入404，
{
        path: 'packages/react/components/:children/',
        component: contentTmpl,
      }

**Comment by ycjcl868** [comment]
有 demo 吗？

**Comment by jinyindu** [comment]
![image](https://user-images.githubusercontent.com/18224886/56179382-121f7f80-6038-11e9-8fcf-846285961f71.png)
![image](https://user-images.githubusercontent.com/18224886/56179387-18156080-6038-11e9-9e52-7b25a52477a1.png)
![image](https://user-images.githubusercontent.com/18224886/56179402-29f70380-6038-11e9-8dc5-cfe4c11c0a64.png)
我看了一下antd design中 components只有一层，我有个需求 要做成packages包 层级有三层，我这样配置路由一直是404 不知道是bisheng不能支持吗

**Comment by jinyindu** [comment]
demo2.zip

**Comment by jinyindu** [comment]
麻烦看一下 我配置的对吗 已经困扰好几天了

**Comment by jinyindu** [comment]
bisheng的文档好少啊

**Comment by Renascence** [comment]
多级路由是这样:
```
{
    path: '/posts/:type/:component/:post',
    dataPath: '/:type/:component/:post',
    component: './template/Post',
 }
```
