### ISSUE TITLE
Firefox 下点击锚点时会跳到页面顶部

### ISSUE THREAD

**Issue by afc163** [benjycui/bisheng#20]
http://ant.design/components/button#components-button-demo-basic

**Comment by benjycui** [comment]
这个是浏览器的默认行为吧。。

**Comment by afc163** [comment]
这不是浏览器的默认行为吧，点击下面的锚点也会跳到顶部。

正确的行为应该是滚动到对应的 demo 顶部，并高亮。

**Comment by afc163** [comment]
。。。这个问题是在 Firefox 下才能重现。试了 Chrome 下是对的。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/bcc07d06f19523a299c4d8f28a5c8dabf327b3e8
