### ISSUE TITLE
bisheng 在window下themePath出错

### ISSUE THREAD

**Issue by maxid** [benjycui/bisheng#26]
ERROR in ./~/bisheng/lib/entry.nunjucks.js
Module not found: Error: Cannot resolve module 'D:ant-designsite        heme' in D:\ant-design\node_modules\bisheng\lib
 @ ./~/bisheng/lib/entry.nunjucks.js 14:12-47

ERROR in ./~/bisheng/lib/utils/template-wrapper.nunjucks.js
Module not found: Error: Cannot resolve module 'D:ant-designsite        heme/template/NotFound' in D:\ant-design\node_modules\bisheng\lib\utils
 @ ./~/bisheng/lib/utils/template-wrapper.nunjucks.js 7:15-68

ERROR in ./~/bisheng/lib/utils/template-wrapper.nunjucks.js
Module not found: Error: Cannot resolve module 'D:ant-designsite        heme' in D:\ant-design\node_modules\bisheng\lib\utils
 @ ./~/bisheng/lib/utils/template-wrapper.nunjucks.js 46:17-83

ERROR in ./~/bisheng/lib/utils/data.js
Module parse failed: D:\ant-design\node_modules\bisheng\lib\loaders\bisheng-data-loader.js?config=D:\ant-design\site\bisheng.config.js!D:\ant-design\node_modules\bisheng\lib\utils\data.js Line 18: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
|   'components\back-top\demo\custom': require('D:\ant-design\components\back-top\demo\custom.md'),
|   'components\back-top\index': require('D:\ant-design\components\back-top\index.md'),
|   'components\badge\demo\99plus': require('D:\ant-design\components\badge\demo\99plus.md'),
|   'components\badge\demo\basic': require('D:\ant-design\components\badge\demo\basic.md'),
|   'components\badge\demo\change': require('D:\ant-design\components\badge\demo\change.md'),
 @ ./~/bisheng/lib/utils/template-wrapper.nunjucks.js 8:11-31

**Comment by benjycui** [comment]
直接在 ant-design 项目中 `npm start` 就报错是吧？

**Comment by maxid** [comment]
是的

**Comment by azl397985856** [comment]
遇到同样的问题， window兼容问题

**Comment by benjycui** [comment]
Windows 兼容问题现在没精力折腾，要不你们试下用 http://www.mingw.org/ ?

**Comment by hellowenqi** [comment]
楼主，‘./~/bisheng/lib/utils/data.js’ 这个问题有解决吗?

**Comment by benjycui** [comment]
麻烦详细描述问题。

**Comment by forleve** [comment]
window环境下，使用ant-design，报如下错误
ERROR in ./~/bisheng/lib/utils/data.js
Module parse failed: F:\ant-design\node_modules\bisheng\lib\loaders\bisheng-data-loader.js?config=F:/ant-design/site/bisheng.config.js&isBuild=undefined!F:\ant-design\node_modules\bisheng\lib\utils\data.js Line 166: Unexpected token ILLEGAL
You may need an appropriate loader to handle this file type.
| },
|   },
|   'components\badge\demo\99plus': function () {
|   return new Promise(function (resolve) {
|     require.ensure([], function (require) {
 @ ./~/bisheng/tmp/entry.index.js 19:11-42


试过mingw不能解决问题，似乎是markdown解析有问题，能不能抽空看一下？

**Comment by benjycui** [comment]
http://enclose.io/

**Comment by benjycui** [comment]
不知道用这个可以不。。 https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by pengxiaobao** [comment]
遇到同样的问题， 上面方法试了下，也不行。

**Comment by benjycui** [comment]
+ bisheng@0.20.2

**Comment by febobo** [comment]
@benjycui 
没有人用mac 遇到类似问题 ?

version: 0.24.2
system: Mac

同样遇到楼上的data.js 找不到的问题
![image](https://user-images.githubusercontent.com/9276376/29710043-4b403ae2-89c1-11e7-8827-feb28e0b1b73.png)

**Comment by benjycui** [comment]
@febobo ant-design 就是这个版本 https://github.com/ant-design/ant-design/blob/319fa7c82da39603f07b57cdefa60337805c4e90/package.json#L92 Mac 下没问题，建议你提供可重现 repo
