### ISSUE TITLE
默认载入 theme/static 下的静态文件导致不可控

### ISSUE THREAD

**Issue by noyobo** [benjycui/bisheng#30]
例如：static 下的 less css 等。 

https://github.com/benjycui/bisheng/blob/1036f226eeeef73d417b2c06d91caeda10138b82/lib/utils/template-wrapper.nunjucks.js#L38

**Comment by noyobo** [comment]
有点不理解 😇. 如果指定特定的后缀 `.jsx`

```const Template = require(`{{ themePath }}/${template.replace(/^\.\//, '')}.jsx`);```

就不会载入 静态文件. 而且这里的 template 也没匹配到  static 的路径.

**Comment by benjycui** [comment]
`require('site/theme/' + sth)` 时，Webpack 会把 `site/theme` 下面的文件全部都打包进来，然后根据运行时计算的结果返回相应的模块。

**Comment by benjycui** [comment]
这对 JS 是没什么影响的，就是文件比较大而已，但是对样式就有坑。

**Comment by benjycui** [comment]
0.7.4
