### ISSUE TITLE
windows下由于路径中存在反斜杠，无法正确解析

### ISSUE THREAD

**Issue by GrayChoi** [benjycui/bisheng#35]
![default](https://cloud.githubusercontent.com/assets/10493353/17198651/07861014-54b2-11e6-998a-5c0a50ef148b.PNG)

themePath中存在反斜杠，require的时候直接忽略了。

**Comment by hellowenqi** [comment]
the same problem

**Comment by benjycui** [comment]
Duplicated: https://github.com/benjycui/bisheng/issues/26

**Comment by benjycui** [comment]
+ bisheng@0.20.2
