### ISSUE TITLE
Ctrl+C 无法终结进程

### ISSUE THREAD

**Issue by afc163** [benjycui/bisheng#43]
再次启动时会报端口占用。

```
Error: listen EADDRINUSE :::8001
```

**Comment by yesmeck** [comment]
我也碰到了，好像是 atool-build 的缘故，在 build 的时候 ctrl+c 就会这样。

**Comment by yesmeck** [comment]
在 react-component/table 里也会有这样的情况。

**Comment by yesmeck** [comment]
应该是 dora-plugin-webpack 的缘故，没有捕捉`process.exit`。
