### ISSUE TITLE
[HELP] bisheng 我要用 hashHistory！

### ISSUE THREAD

**Issue by jsrider** [benjycui/bisheng#44]
router 我要用 hashHistory！ 该怎么配置？

```

const router = React.createElement(ReactRouter.Router, {
  history: ReactRouter.useRouterHistory(history.createHistory)({
    basename: '/',
  }),
  routes: processedRoutes,
  createElement,
});
```
to 

```

const router = React.createElement(ReactRouter.Router, {
  history: ReactRouter.hashHistory,
  routes: processedRoutes,
  createElement,
});
```

**Comment by benjycui** [comment]
react-router 官方并不推荐用 hashHistory https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#browserhistory

使用场景是怎样？

**Comment by jsrider** [comment]
我们这边部署到test，访问子path，刷新了 就 404~ 
我们没有部署在站点更目录，PHP会做路由

**Comment by zzswang** [comment]
如果你是nginx的话，你可以更改 你的 site 配置，比如访问 /test/your/path locate 到 /test/index.html

比如

```
       location ~* /test/(\w+) {
                 try_files $uri /test/$1/index.html =404;
        }
```

**Comment by benjycui** [comment]
有 Server 端的话，可以配置路由。没 Server 时，`bisheng build` 也会生成静态目录，不应该 404 的。

**Comment by jsrider** [comment]
谢谢各位~ 跟我们PHP 同学转达了，我们这边框架默认路由到另一个入口的，具体不是很清楚，总之他说没法实现。 所以只能用 hashhistory 了~

**Comment by ganxunzou** [comment]
@jsrider hashhistory 怎么改的
