### ISSUE TITLE
两个react版本冲突怎么解决

### ISSUE THREAD

**Issue by mosikoo** [benjycui/bisheng#54]
bisheng的react的版本是15.4.1。  我的库的react的版本是14.8.2
然后引起以下问题（因为用了两个版本的react）

```javascript
nhandled rejection Invariant Violation: addComponentAsRefTo(...): 
Only a ReactOwner can have refs.
```

本来我觉得bisheng.config.js中webpack设置下externals就可以了

```javascript
    config.externals = {
       react: 'React',
       'react-dom': 'ReactDOM'
     };
```

结果报错  react is not defined

不知道怎么解决了

**Comment by mosikoo** [comment]
目前手动删掉node_modules/bisheng/react包 可以解决问题，但是不知道bisheng.config.js中怎么设置

**Comment by mosikoo** [comment]
好吧， 设置了webpack 的alias，已经解决了。。给后续的人一个参考

**Comment by benjycui** [comment]
为什么自己还要引进一个 React。。。直接用 bisheng 提供的就好。

**Comment by JackFrankWen** [comment]
我也遇到了这个问题，因为项目版本还是15.6.1的，没法升级，，太大了，现在打算搞个公用库，
