### ISSUE TITLE
优化点

### ISSUE THREAD

**Issue by warmhug** [benjycui/bisheng#55]
- webpack 支持设置 externals 、能直接使用 cdn 的 react/react-dom 等。现在是 react / reac-dom 都直接打包进来 https://mobile.ant.design/common.js
- css 做到按需加载。现在是所有 css 不管用到与否、都加载了进来 https://mobile.ant.design/kitchen-sink.css

这些都比较严重的影响移动端网页加载性能，希望尽早优化！

**Comment by pingan1927** [comment]
这个如果使用按需加载策略 是可以都做到想要的效果，没明白你想说的是什么问题

**Comment by benjycui** [comment]
> webpack 支持设置 externals 、能直接使用 cdn 的 react/react-dom 等。现在是 react / reac-dom 都直接打包进来 https://mobile.ant.design/common.js

第一点现在就可以 https://github.com/benjycui/bisheng#webpackconfig-config--config

**Comment by benjycui** [comment]
> css 做到按需加载。现在是所有 css 不管用到与否、都加载了进来 https://mobile.ant.design/kitchen-sink.css

第二点空了我确认下是否 source 配置的问题。

**Comment by warmhug** [comment]
> 如果需要对内置的 webpack 配置进行修改, 可在项目根目录新建 webpack.config.js 进行扩展.

为什么在 bisheng.config.js 文件里的  webpackConfig(config) {} 里没法修改？

现在为了聚宝/网商等上层 ui 库 直接能复用 网站代码，想每个 theme 只有一个配置文件即可、里边不仅放bisheng 必须的 router 等配置，也想放网站标题、菜单文案等配置项。

**Comment by benjycui** [comment]
> 为什么在 bisheng.config.js 文件里的 webpackConfig(config) {} 里没法修改？

这个可以在 webpackConfig 里面改的啊。。

> 现在为了聚宝/网商等上层 ui 库 直接能复用 网站代码，想每个 theme 只有一个配置文件即可、里边不仅放bisheng 必须的 router 等配置，也想放网站标题、菜单文案等配置项。

这个需要支持把 npm 包作为 theme，如：

```js
{
  theme: 'bisheng-them-one',
}
```

**Comment by warmhug** [comment]
webpackConfig 里可以改，没问题，可能之前搞错了。

> css 做到按需加载。现在是所有 css 不管用到与否、都加载了进来 https://mobile.ant.design/kitchen-sink.css

这个要优先搞下，影响到上层 ui 库的开发了。
