### ISSUE TITLE
one-theme 如何添加图片？

### ISSUE THREAD

**Issue by yozman** [benjycui/bisheng#65]
搭建了一个使用 bisheng 来驱动的博客
https://yozman.github.io/ggw

如何为文章添加静态图片呢？
主题使用的是 `bisheng-one-theme`

**Comment by benjycui** [comment]
就是 Markdown 的语法即可。

**Comment by yozman** [comment]
@benjycui 
文件存到哪里呢？路径有什么要求？

**Comment by benjycui** [comment]
Please learn [how to write readable Markdown](https://guides.github.com/features/mastering-markdown/).

就是普通的 Markdown

**Comment by yozman** [comment]
@benjycui 
markdown 我会写 :sob: 
我是说图片存的文件夹名有什么特别的要求么？
比如像文章的话，默认是 `posts` 文件夹

**Comment by benjycui** [comment]
没有，为什么就不试试先呢？

**Comment by afc163** [comment]
楼主的意思是如何存储图片吧，一般来说，最好使用 cdn 图床，自己去找一个合适的吧。

**Comment by yozman** [comment]
@benjycui 
想弄得更规范些 :sob: 
问题已解决
