### ISSUE TITLE
site的路由问题

### ISSUE THREAD

**Issue by zhangking** [benjycui/bisheng#67]
你好，我想build后生成的site应该是一个静态站点，我打开跳404了，请问下是什么原因，应该如何使用

**Comment by benjycui** [comment]
重现 repo 和重现步骤？

**Comment by zhangking** [comment]
我用的是2.6.0分支， 然后跑 npm run site 然后把_site目录里的index.html文件的静态资源url改成了相对路径（默认是绝对/）打开index.html 会闪一下首页 然后跳404了

**Comment by benjycui** [comment]
路由问题，路由配置没有 `.html` 后缀，你直接查看静态文件肯定不行。

本地跑一个 `python -m SimpleHTTPServer` 之类即可。
