### ISSUE TITLE
webpack config加入sass-loader后。

### ISSUE THREAD

**Issue by gx761** [benjycui/bisheng#68]
从命令行全局运行bisheng start -c 'xxx.config.js'没问题，但是用npm run script就报错。

```bash
ERROR in ./~/atool-build/~/css-loader?importLoaders=2&sourceMap!./~/atool-build/~/autoprefixer/lib/autoprefixer.js?browsers=last 2 version!./~/atool-build/~/sass-loader/lib/loader.js?outputStyle=expanded&sourceMap!./demoSite/src/static/index.scss
Module build failed: CssSyntaxError: /css-loader!/Users/royguo/Documents/www/componentSystem/node_modules/atool-build/node_modules/autoprefixer/lib/autoprefixer.js?browsers=last 2 version!/Users/royguo/Documents/www/componentSystem/node_modules/atool-build/node_modules/sass-loader/lib/loader.js?outputStyle=expanded&sourceMap!/Users/royguo/Documents/www/componentSystem/demoSite/src/static/index.scss:2:7: Unknown word
```

估计跟atool-build有关。这是啥情况恩。

**Comment by benjycui** [comment]
配置 sass-loader 时用绝对路径 `/path-to/sass-loader`

**Comment by noyobo** [comment]
CssSyntaxError  Unknown word，

`/Users/royguo/Documents/www/componentSystem/demoSite/src/static/index.scss`

应该是这个文件存在语法错误。

**Comment by gx761** [comment]
ERROR in /Users/royguo/Documents/www/componentSystem/node_modules/atool-build/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!/Users/royguo/Documents/www/componentSystem/node_modules/style-loader/index.js!/Users/royguo/Documents/www/componentSystem/node_modules/css-loader/index.js!/Users/royguo/Documents/www/componentSystem/node_modules/sass-loader/lib/loader.js!/Users/royguo/Documents/www/componentSystem/libraries/commons/mod-progress/style/index.scss doesn't export content

错误是这样的，可以看到除了extract text之外，其他用的都是我node_modules里面的loader, 都是webpack2的，全局运行bisheng build xxx没问题，但是用node_modules里面装的bisheng 就说doesn't export content.

**Comment by gx761** [comment]
问题解决了，原因是我在bisehng.comon.config.js里面，添加sass loader 并用extact-text-webpack-plugin的时候没有去新实例化一个ExtractTextPlugin，然后可能和atool里面用在less loader那的那句冲突了。
