### ISSUE TITLE
`npm start`之后CPU一直100%

### ISSUE THREAD

**Issue by pixystone** [benjycui/bisheng#71]
之前dora也遇到，应该是同一个问题。[dora-js/dora#91](https://github.com/dora-js/dora/issues/91)

只要node版本6+就会发生。

[“node”的取样.txt](https://github.com/benjycui/bisheng/files/824438/node.txt)

**Comment by benjycui** [comment]
然而我看不懂。

**Comment by noyobo** [comment]
如果是版本原因，现在都已经 7.x 了。 再尝试下，如果没有问题，可以关闭这个 issue。

**Comment by pixystone** [comment]
使用高版本重新`tnpm install`装一次依赖能解决。
