### ISSUE TITLE
Support accessing more variables (for example, config) in `template.html`

### ISSUE THREAD

**Issue by breeswish** [benjycui/bisheng#74]

**Comment by benjycui** [comment]
Use case?

**Comment by breeswish** [comment]
`template.html` is the base foundation for all rendered pages.
let's say, want to reference some precompiled file in <script> or <link> while keeping configurable.

**Comment by paranoidjk** [comment]
I will PR to do this feature.

Add a `config.htmlTemplateVariable: object` api, support to pass more data to nunjucks template.

The use case is https://github.com/ant-design/ant-design/issues/7383#issuecomment-325630430

**Comment by afc163** [comment]
Try https://webpack.js.org/plugins/html-webpack-plugin/

**Comment by paranoidjk** [comment]
@afc163 https://github.com/benjycui/bisheng/blob/master/packages/bisheng/src/index.js#L59

**Comment by paranoidjk** [comment]
@breeswish see https://github.com/benjycui/bisheng/pull/99. Will not expose `config`, but i will give a `config.htmlTemplateExtraData`, i think it will be enough.
