### ISSUE TITLE
Support post-process plugins?

### ISSUE THREAD

**Issue by breeswish** [benjycui/bisheng#77]
It seems that current plugins are applied to every markdown file (act as "transform func"). How to write post-process plugins? (that is, applied after all markdown files are processed, act as "done func").

I would like to generate a list sorted by fields in the markdown file meta to the config file, which requires knowledge of all markdown documents and I don't want to write my own "document scanner".

It would be great to provide ways to manipulate this:
https://github.com/benjycui/bisheng/blob/6a19ea194941ca92b10c31210c35a170b3e420cb/packages/bisheng/src/loaders/bisheng-data-loader.js#L67

**Comment by benjycui** [comment]
Ref: https://github.com/benjycui/bisheng/issues/68

**Comment by breeswish** [comment]
Thanks but this issue isn't about post-processing assets in webpack.

**Comment by benjycui** [comment]
So, make a mistake, `post-process` => `post-css`...

**Comment by benjycui** [comment]
Actually, you can control the order of plugin to control the order of processing.
