### ISSUE TITLE
Lazy load not lazying loading

### ISSUE THREAD

**Issue by breeswish** [benjycui/bisheng#78]
```js
module.exports = {
  source: './posts',
  output: './_site',
  theme: 'bisheng-theme-one',
  port: 8000,
};
```

Command:

```bash
bisheng build --ssr
```

Result:

In `_site/index.js`, I can see contents of all posts. They are not lazy-loaded at all. All articles are embedded in the JavaScript file :(

https://github.com/benjycui/bisheng/blob/ef82970dd08ee08325ec090de68e8085fcf3ff5e/packages/bisheng/src/utils/source-data.js#L84

According to the code, lazy load is not enabled in SSR.

**Comment by benjycui** [comment]
开启 `--ssr` 后会有这个问题。
