### ISSUE TITLE
Remain functional even with js turned off

### ISSUE THREAD

**Issue by dyu** [benjycui/bisheng#85]
I disabled js on http://benjycui.github.io/bisheng/ and the navigation no longer works.
With phenomic (static-gen, also react-based), the site would continue to work.

**Comment by benjycui** [comment]
Yep, it's a bug while using [`config.root`](https://github.com/benjycui/bisheng#root-string), and it will works fine if you are not using `config.root`, e.g. https://ant.design/index-cn

**Comment by benjycui** [comment]
How about a PR?

**Comment by benjycui** [comment]
Just ignore this, it's impossible to solve the problem in bisheng. Need to update link in users' code.
