### ISSUE TITLE
部署使用文档能详细点吗，看不太懂

### ISSUE THREAD

**Issue by opspy** [benjycui/bisheng#91]
部署使用文档能详细点吗，看不太懂

**Comment by benjycui** [comment]
比如说？

**Comment by zilan830** [comment]
可以展示一个使用案例吗？我也有点摸不清头绪。这个是可以html和markdowm混写还是怎么？谢谢

**Comment by benjycui** [comment]
https://github.com/benjycui/bisheng/tree/master/packages/bisheng-example
