### ISSUE TITLE
当服务器虚拟目录下不自动映射index.html时，路由不能自动定位

### ISSUE THREAD

**Issue by aibaiejoy** [benjycui/bisheng#94]
你好，我的服务器不能自动映射index.html，直接访问/xx/index.html路由会定位到404，这个问题怎么解决，希望能和你钉钉沟通下，@虬进

**Comment by benjycui** [comment]
需要配置服务器，把：

```bash
/ => /index.html
/article => /article.html
```

这个查下你的服务器如 Nginx 的配置把。

**Comment by aibaiejoy** [comment]
这个我知道，通过配置服务器可以实现，但是服务器是一个公共的静态服务器。我没有权限修改，能不能改成使用呢hashHistory呢

**Comment by benjycui** [comment]
不能。。

下面这种映射如果服务器不支持，那么改成 hashHistory 也没用的。

```bash
/ => /index.html
/article => /article.html
```
