### ISSUE TITLE
externals react后报错

### ISSUE THREAD

**Issue by zhangking** [benjycui/bisheng#96]
我在webpack里设置了 把react，react-dom以及react-router externals，然后运行报错找不到react，已经在template.html script tag引入了

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design-mobile/blob/40dc59f2bbe9c6df4e1afaa652c72fbcf2638751/site/bisheng.common.config.js#L7-L13

Usage question, please study webpack by yourself.
