### ISSUE TITLE
关于路由

### ISSUE THREAD

**Issue by DonSpeng** [benjycui/bisheng#98]
bisheng是把md文档转化为网页（可以这么理解吧），想问一下路由的使用怎么办？想做一个类似antd官网的说明性网站，有没有关于bisheng的路由说明，我看官方文档中说bisheng是结合了react-router的

**Comment by benjycui** [comment]
See: https://github.com/benjycui/bisheng/issues/17

**Comment by DonSpeng** [comment]
谢谢，刚才不好意思了。。。。。
